export const [RECIPE_NAMES, RECIPE_OPTIONS] = (() => {

  const recipe_names = [
    [1, 'Apples, baked'], [2, 'Bacon, oven fried'], [3, 'Bacon, oven fried, precooked'], [4, 'Bagel, w/cream cheese'],
    [5, 'Bagels'], [6, 'Banana Split'], [7, 'Bar, hermits'], [8, 'Bar, nut, chewy'], [9, 'Bar, raisin nut'],
    [10, 'Bar, toffee, crisp'], [11, 'Batter, frying'], [12, 'Batter, tempura'], [13, 'Beans, baked, Boston'],
    [14, 'Beans, baked, cnd'], [15, 'Beans, baked, Italian'], [16, 'Beans, green, combo'], [17, 'Beans, green, herbed'],
    [18, 'Beans, green, parisienne, f/cnd'], [19, 'Beans, green, w/corn, fzn'], [20, 'Beans, kidney/pinto/white'],
    [21, 'Beans, lyonnaise/green/wax'], [22, 'Beans, refried, w/cheese'], [23, 'Beans, Spanish'],
    [24, 'Beef, chipped, creamed'], [25, 'Beef, cordon bleu'], [26, 'Beef, corned'], [27, 'Beef, cubes, w/bbq sauce'],
    [28, 'Sauce, barbecue'], [29, 'Beef, ground, cordon bleu'], [30, 'Beef, ground, creamed'],
    [31, 'Beef, ground, hamburger, w/parmesan'], [32, 'Sauce, pizza'], [33, 'Beef, liver, breaded, fried'],
    [34, 'Beef, pepper steak'], [35, 'Beef, pot roast'], [36, 'Beef, rib pot roast'], [37, 'Beef, roast'],
    [38, 'Beef, simmered'], [39, 'Beef, steak, country'], [40, 'Beef, steak, grilled'], [41, 'Beef, steak, ranchero'],
    [42, 'Beef, steak, teriyaki'], [43, 'Beets, Harvard'], [44, 'Beets, spiced, hot'], [45, 'Biscuits, bkg pwd'],
    [46, 'Bread, banana'], [47, 'Bread, corn'], [48, 'Bread, corn, f/dry mix'], [49, 'Bread, croutons'],
    [50, 'Bread, white'], [51, 'Bread, French'], [52, 'Wash, cornstarch'], [53, 'Bread, garlic, toasted'],
    [56, 'Bread, Irish soda'], [57, 'Bread, oatmeal'], [58, 'Bread, pumpkin'], [59, 'Bread, raisin'],
    [60, 'Bread, rye'], [61, 'Wash, egg white'], [63, 'Bread, white, short-time formula'],
    [64, 'Bread, whole wheat, w/wheat base'], [65, 'Broccoli, herbed'], [66, 'Broccoli, parmesan'],
    [67, 'Broccoli, w/corn & carrots'], [68, 'Brownies'], [69, 'Brownies, apple cake'], [70, 'Brownies, butterscotch'],
    [71, 'Brussels Sprouts, superba'], [72, 'Brussels Sprouts, w/corn & carrot'], [73, 'Buns, hot cross'],
    [74, 'Wash, egg'], [75, 'Glaze, syrup'], [76, 'Frosting, decorator'], [77, 'Burrito, breakfast'],
    [78, 'Cabbage, fried'], [79, 'Cabbage, red, w/sweet & sour sauce'], [80, 'Cabbage, rolls, stuffed'],
    [81, 'Cake, angel food'], [82, 'Cake, applesauce'], [83, 'Cake, banana, f/yellow dry mix'],
    [84, 'Cake, carrot, f/dry mix'], [85, 'Cake, chocolate macaroon, f/dry mix'], [86, 'Glaze, vanilla'],
    [87, 'Cake, crumb/snickerdoodle'], [88, 'Cake, devil\'s food'], [89, 'Cake, easy chocolate'],
    [90, 'Cake, easy vanilla'], [91, 'Cake, Florida lemon'], [92, 'Cake, gingerbread'], [93, 'Cake, jelly roll'],
    [94, 'Cake, peanut butter crumb'], [95, 'Cake, pineapple crunch'], [96, 'Cake, pineapple upside down'],
    [97, 'Cake, yellow, f/dry mix'], [98, 'Cake, pound'], [99, 'Cake, quick coffee, f/biscuit mix'],
    [100, 'Cake, spice'], [101, 'Cake, strawberry, f/dry mix'], [102, 'Cake, white'], [103, 'Cake, yellow'],
    [104, 'Cake, yellow cupcakes'], [106, 'Carrots, marinated'], [107, 'Cauliflower,  au gratin'],
    [108, 'Cauliflower, French fried'], [109, 'Cauliflower, w/peas & carrots'],
    [110, 'Celery, stuffed, w/pimiento cheese'], [111, 'Cereal, hot, oatmeal'], [112, 'Chalupa'], [113, 'Cheesecake'],
    [114, 'Chicken, bkd'], [115, 'Chicken, bombay, bkd'], [116, 'Chicken, breast, Caribbean'],
    [117, 'Chicken, buffalo'], [118, 'Chicken, Chinese five-spice'], [119, 'Chicken, creole'], [120, 'Sauce, creole'],
    [121, 'Chicken, fillets, oven fried'], [122, 'Chicken, fried'], [123, 'Chicken, honey ginger'],
    [124, 'Chicken, hot & spicy'], [125, 'Chicken, oven bkd'], [126, 'Chicken, parmesan'],
    [127, 'Chicken, savory baked'], [128, 'Chicken, szechwan'], [129, 'Sauce, szechwan'], [130, 'Chicken, teriyaki'],
    [131, 'Sauce, teriyaki marinade'], [132, 'Chicken, w/bbq sauce'], [133, 'Chicken, w/gravy, baked'],
    [134, 'Chicken, w/orange sauce'], [135, 'Chicken, w/pineapple sauce'], [136, 'Chicken, w/yogurt, baked'],
    [137, 'Chili Dog, w/cheese & onion'], [138, 'Chili, con carne'], [139, 'Chili, con carne, w/beans, cnd'],
    [140, 'Chili, w/o beans'], [141, 'Clams, strips, breaded, baked'], [142, 'Cobbler, apple'],
    [143, 'Crust, pie, 13 - 1 crust pies'], [144, 'Coffee, f/automatic coffee maker'], [145, 'Coffee, f/automatic urn'],
    [146, 'Coffee, f/instant freeze-dried'], [147, 'Cole Slaw'], [148, 'Cole Slaw, German'],
    [149, 'Cole Slaw, w/creamy dressing'], [150, 'Collard Greens, Southern style'], [151, 'Cookies, chocolate chip'],
    [152, 'Cookies, chocolate drop'], [153, 'Cookies, coconut cereal'], [154, 'Cookies, coconut raisin drop'],
    [155, 'Cookies, crisp chocolate'], [156, 'Cookies, crisp drop'], [157, 'Cookies, ginger molasses'],
    [158, 'Cookies, gingerbread, f/dry cake mix'], [159, 'Cookies, lemon'], [160, 'Cookies, oatmeal'],
    [161, 'Cookies, oatmeal, f/mix'], [162, 'Cookies, peanut butter'], [163, 'Cookies, shortbread'],
    [164, 'Cookies, sugar'], [165, 'Corn Dog'], [166, 'Corn, calico'], [167, 'Corn, scalloped cream style'],
    [168, 'Corn, w/green beans & carrots'], [169, 'Cornish Hens, rock, honey glazed'], [170, 'Crab, cakes'],
    [171, 'Cream Puffs'], [172, 'Crisp, apple'], [173, 'Crisp, peach'], [174, 'Crust, graham cracker'],
    [176, 'Crust, pie, 13 - 2 crust pies'], [177, 'Danish, diamonds, f/danish pastry dough'],
    [179, 'Dessert, fruit cup'], [180, 'Dessert, fruit cup, fluffy'], [181, 'Dish, bean, combo'],
    [182, 'Dish, beans, red, w/rice'], [183, 'Dish, beef & noodles, braised'], [184, 'Dish, beef, balls, stroganoff'],
    [185, 'Dish, beef, corned, New England'], [186, 'Dish, beef, egg foo young'], [187, 'Dish, beef, minced'],
    [188, 'Dish, beef, rolls, stuffed'], [189, 'Gravy, brown'], [190, 'Dish, beef, sukiyaki'],
    [191, 'Dish, broccoli, polonaise'], [192, 'Dish, broccoli, w/cheese & rice'],
    [193, 'Dish, cabbage, Chinese, fried'], [194, 'Dish, carrots, amandine, w/celery'],
    [195, 'Dish, carrots, lyonnaise'], [196, 'Dish, carrots, w/orange amandine'], [197, 'Dish, catfish, Caribbean'],
    [198, 'Dish, chicken & rice, baked'], [199, 'Dish, chicken, a la king'], [200, 'Dish, chicken, adobo'],
    [201, 'Dish, chicken, cacciatore'], [202, 'Dish, chicken, chow mein'], [203, 'Dish, chicken, fiesta'],
    [204, 'Dish, chicken, tetrazzini'], [205, 'Dish, chicken, vega'], [206, 'Dish, chili & macaroni, f/cnd chili'],
    [207, 'Dish, chili, conquistador'], [208, 'Dish, chilies rellenos'], [209, 'Dish, chop suey, pork'],
    [210, 'Dish, egg roll, w/meat, Chinese'], [211, 'Dish, eggplant, parmesan'], [212, 'Dish, spaghetti, w/meat sauce'],
    [213, 'Dish, enchiladas, beef'], [214, 'Gravy, chili style'], [215, 'Dish, enchiladas, chicken'],
    [216, 'Dish, fajitas, beef'], [217, 'Dish, fish, stuffed, baked'], [218, 'Dish, frankfurters, w/sauerkraut, bkd'],
    [219, 'Dish, frittata, potatoes'], [220, 'Dish, frittata, rice'], [221, 'Dish, goulash, Hungarian'],
    [222, 'Dish, green peppers, stuffed'], [223, 'Sauce, tomato'], [224, 'Dish, ham & noodles, scalloped'],
    [225, 'Dish, ham & potatoes, scalloped'], [226, 'Dish, jaegerschnitzel, veal, w/sauce'], [228, 'Dish, Jambalaya'],
    [229, 'Dish, lasagna'], [230, 'Dish, lasagna, w/spinach'], [231, 'Dish, liver, w/onions, braised'],
    [232, 'Dish, macaroni & cheese, baked'], [233, 'Dish, macaroni, creole'],
    [234, 'Dish, macaroni, w/ham & tomatoes, bkd'], [235, 'Dish, manicotti/cannelloni, beef'],
    [236, 'Dish, meatballs, Swedish'], [237, 'Dish, meatloaf'], [238, 'Dish, noodles, Jefferson'],
    [239, 'Dish, peppers, stuffed'], [241, 'Dish, pie, beef & corn, w/potatoes'], [242, 'Potatoes, mashed'],
    [243, 'Dish, pie, cnd beef, w/biscut'], [245, 'Dish, porcupine balls, beef'], [247, 'Dish, pork, adobo'],
    [248, 'Dish, pork, sweet & sour'], [249, 'Dish, pot pie, beef,  w/biscuit topping'], [251, 'Dish, pot pie, turkey'],
    [252, 'Dish, quiche, w/mushrooms'], [253, 'Dish, ravioli, beef, w/sauce'], [254, 'Dish, rice, Mexican'],
    [255, 'Dish, rice, Spanish'], [256, 'Dish, sauerbraten'], [257, 'Dish, seafood, newburg'],
    [258, 'Dish, shrimp, creole'], [261, 'Dish, spaghetti, w/meatballs'], [262, 'Dish, steak, salisbury'],
    [263, 'Dish, steak, w/onions'], [264, 'Dish, stroganoff, w/beef'], [265, 'Dish, Swiss steak, w/tomato sauce'],
    [266, 'Dish, tamale pie'], [267, 'Dish, tortellini, cheese, w/marinara'], [268, 'Sauce, marinara'],
    [269, 'Dish, tuna & noodles, baked'], [270, 'Dish, tuna, chopstick'], [271, 'Dish, turkey & noodles, baked'],
    [272, 'Dish, turkey, curry'], [273, 'Dish, vegetable, stir fry'], [274, 'Dish, vegetables, tempura'],
    [275, 'Dish, yakisoba/beef & spaghetti'], [276, 'Dough, sweet'], [277, 'Doughnut, cake'], [278, 'Doughnut, raised'],
    [279, 'Drink, cranberry & orange, cocktail'], [280, 'Drink, fruit flvr, dry mix'], [281, 'Drink, fruit punch'],
    [282, 'Drink, orange & pineapple, cocktail'], [283, 'Drink, orangeade'], [284, 'Drink, tomato juice, cocktail'],
    [285, 'Duck, roasted'], [286, 'Dumplings'], [287, 'Eggs, au gratin/Scotch woodcock'], [288, 'Eggs, deviled'],
    [289, 'Eggs, griddle fried, cooked to order'], [290, 'Eggs, hard cooked'], [291, 'Eggs, poached, cooked to order'],
    [292, 'Eggs, scrambled'], [293, 'Eggs, soft cooked'], [294, 'English Muffin'],
    [295, 'English Muffin, w/bacon egg cheese'], [296, 'Filling, cherry, w/cornstarch'],
    [297, 'Filling, cinnamon sugar'], [298, 'Filling, nut'], [299, 'Filling, pineapple pregelatinize starch'],
    [300, 'Fish, baked'], [301, 'Fish, catfish, fillet, southern fried'], [302, 'Fish, chipper'],
    [303, 'Fish, oven fried'], [304, 'Fish, pan fried'], [305, 'Fish, parmesan'], [306, 'Fish, portions, baked'],
    [307, 'Fish, spicy, baked'], [308, 'Flounder, creole, stuffed'], [310, 'French Toast'], [311, 'French Toast, puff'],
    [313, 'Fritters, apple'], [314, 'Fritters, corn'], [315, 'Frosting, brown sugar'], [316, 'Frosting, butter cream'],
    [317, 'Frosting, caramel'], [318, 'Frosting, chocolate chip fudge'], [319, 'Frosting, chocolate fudge'],
    [320, 'Frosting, chocolate glaze'], [321, 'Frosting, chocolate, frosting/Icing mix'],
    [322, 'Frosting, coconut pecan'], [323, 'Frosting, cream cheese'], [325, 'Frosting, peanut butter cream'],
    [326, 'Frosting, vanilla, f/icing mix, pwded'], [327, 'Gelatin, w/fruit'], [328, 'Glaze, strawberry topping'],
    [332, 'Gravy, chicken or turkey, f/base'], [334, 'Gravy, cream style'], [335, 'Gravy, natural pan/au jus'],
    [336, 'Gravy, tomato'], [337, 'Guacamole'], [338, 'Gumbo, okra & tomato'], [339, 'Ham, baked'],
    [340, 'Ham, canned, baked'], [341, 'Ham, steaks, w/bbq sauce'], [342, 'Hamburger, grilled'],
    [343, 'Hamburger, w/soy protein'], [344, 'Hash, corned beef'], [345, 'Hash, roast beef'], [346, 'Hash, Texas'],
    [347, 'Hominy, buttered'], [348, 'Hominy, grits'], [349, 'Hot Cocoa'],
    [350, 'Ice Cream, vanilla, soft serve, f/dry'], [351, 'Ice Cream, vanilla, soft serve, f/liq'], [352, 'Kolaches'],
    [355, 'Lamb, leg, rstd, savory'], [356, 'Lemonade'], [357, 'Lobster, boiled'],
    [358, 'Lunchmeat, beef, oven cooked'], [359, 'Meringue'], [360, 'Muffin'], [361, 'Muffin, applesauce'],
    [362, 'Muffin, bran'], [363, 'Muffin, corn, f/mix'], [364, 'Muffin, oat bran, w/raisins'],
    [365, 'Mushrooms, sauteed'], [366, 'Nachos'], [367, 'Okra, southern fried'], [368, 'Omelet, plain'],
    [369, 'Onions, French fried rings'], [370, 'Onions, fried'], [371, 'Onions, smothered, f/dehyd onions'],
    [372, 'Onions, Spanish'], [373, 'Oysters, fried'], [374, 'Pancakes'], [375, 'Pasta, spaghetti noodles, enriched'],
    [376, 'Pasta, steamed'], [377, 'Peas, w/mushrooms, f/fzn'], [378, 'Pie, apple, cnd, pregelatinized starch'],
    [380, 'Pie, apple, cnd, w/cornstarch'], [382, 'Pie, apple, fried'],
    [383, 'Pie, berry, f/fzn berries, w/cornstarch'], [385, 'Pie, blueberry, cnd, w/cornstarch'],
    [387, 'Pie, blueberry, pregelatinize starch'], [389, 'Pie, butterscotch cream, f/inst mix'],
    [391, 'Pie, cherry crumble'], [392, 'Pie, cherry, cnd, w/cornstarch'],
    [394, 'Pie, cherry, cnd, w/pregelatinize strch'], [396, 'Pie, chocolate & vanilla, f/inst mix'],
    [398, 'Pie, chocolate cream'], [400, 'Pie, chocolate mousse'], [402, 'Pie, coconut, creamy'],
    [404, 'Pie, lemon chiffon'], [406, 'Pie, lemon meringue'], [408, 'Pie, mincemeat'],
    [409, 'Pie, peach, cnd, w/pregelatinize starch'], [411, 'Pie, peach, f/cnd, w/cornstarch'],
    [413, 'Pie, peach, f/fzn, w/cornstarch'], [415, 'Pie, peach, fzn, w/pregelatinize starch'], [417, 'Pie, pecan'],
    [419, 'Pie, pineapple, cnd, w/cornstarch'], [421, 'Pie, pineapple, w/pregelatinize starch'], [423, 'Pie, pumpkin'],
    [425, 'Pie, sweet potato'], [427, 'Pie, vanilla cream'], [429, 'Pie, vanilla cream, f/inst'], [431, 'Pizza'],
    [433, 'Pizza, 12 in, fzn'], [434, 'Pizza, cheese, pita pocket'], [435, 'Pizza, treats'],
    [436, 'Pork, chitterlings, simmered'], [437, 'Pork, chops, braised'], [438, 'Pork, chops, breaded'],
    [439, 'Pork, chops, creole'], [440, 'Pork, chops, Mexicana'], [441, 'Pork, chops, stuffed, baked'],
    [442, 'Pork, chops, sweet & sour'], [443, 'Pork, ham hocks, simmered'], [444, 'Pork, ham loaf, glazed'],
    [445, 'Pork, ham, fresh roasted'], [446, 'Pork, roast'], [447, 'Pork, spareribs, braised'],
    [448, 'Pork, spareribs, Cantonese'], [449, 'Pork, spareribs, sweet & sour'], [450, 'Pork, spareribs, w/bbq sauce'],
    [451, 'Potatoes, au gratin'], [452, 'Potatoes, baked'], [453, 'Potatoes, French fried'],
    [454, 'Potatoes, hashed brown'], [455, 'Potatoes, hashed brown, f/dehyd, sliced'], [456, 'Potatoes, home fried'],
    [458, 'Potatoes, mashed, f/inst'], [459, 'Potatoes, o\'brien'], [460, 'Potatoes, oven browned'],
    [461, 'Potatoes, potato balls, f/inst'], [462, 'Potatoes, potato cakes, German, f/dehyd'],
    [463, 'Potatoes, rissole'], [464, 'Potatoes, scalloped'], [465, 'Potatoes, scalloped, w/onions, dehyd'],
    [466, 'Potatoes, sweet, baked'], [467, 'Potatoes, sweet, candied'], [468, 'Potatoes, sweet, mashed'],
    [469, 'Potatoes, sweet, scalloped, w/apples'], [470, 'Potatoes, w/parsley & butter'], [471, 'Prunes, stewed'],
    [472, 'Pudding, bread'], [473, 'Pudding, rice, baked'], [474, 'Pudding, rice, creamy'], [475, 'Pudding, tapioca'],
    [476, 'Pudding, vanilla cream'], [477, 'Pudding, vanilla cream, f/inst'], [478, 'Rabbit, fried'],
    [479, 'Ratatouille, eggplant & zucchini'], [480, 'Relish, corn'], [481, 'Relish, cranberry orange'],
    [482, 'Rice, pilaf'], [483, 'Rice, pork fried, oven method'], [484, 'Rice, steamed'],
    [485, 'Rice, steamed, steam cooker method'], [486, 'Rolls, hard'], [488, 'Rolls, hot'],
    [489, 'Rolls, hot, short time formula'], [490, 'Rolls, onion'], [491, 'Rolls, submarine/hoagie/torpedo'],
    [493, 'Salad Dressing, blue cheese'], [494, 'Salad Dressing, creamy horseradish'], [495, 'Salad Dressing, French'],
    [496, 'Salad Dressing, creamy Italian'], [498, 'Salad Dressing, garlic French'],
    [499, 'Salad Dressing, honey mustand'], [500, 'Salad Dressing, quick fruit'],
    [501, 'Salad Dressing, red wine vinaigrette'], [502, 'Salad Dressing, Russian'],
    [503, 'Salad Dressing, sour cream'], [504, 'Salad Dressing, tangy'],
    [505, 'Salad Dressing, tangy tarragon, low cal'], [506, 'Salad Dressing, tangy yogurt'],
    [507, 'Salad Dressing, thousand island'], [508, 'Salad Dressing, thousand island, lowcal'],
    [509, 'Salad Dressing, tomato French'], [510, 'Salad Dressing, tomato,  low calorie'],
    [511, 'Salad Dressing, vinaigrette'], [512, 'Salad Dressing, vinegar & oil'],
    [513, 'Salad Dressing, yogurt, low cal'], [514, 'Salad Dressing, zero'],
    [515, 'Salad, apple, w/celery & pineapple'], [516, 'Salad, carrot'], [517, 'Salad, chefs'], [518, 'Salad, chicken'],
    [519, 'Salad, chicken, tropical'], [520, 'Salad, cobb'], [522, 'Salad, confetti rice'],
    [523, 'Salad, cottage cheese'], [524, 'Salad, cottage cheese & peach'], [525, 'Salad, cottage cheese & tomato'],
    [526, 'Salad, cranberry & orange, jellied'], [527, 'Salad, cranberry & pineapple, jellied'],
    [528, 'Salad, cucumber & onion'], [529, 'Salad, frijole'], [530, 'Salad, fruit'],
    [532, 'Salad, fruit cocktail, jellied'], [533, 'Salad, fruit medley'], [534, 'Salad, fruit, jellied'],
    [535, 'Salad, fruit, mixed'], [536, 'Salad, garden cottage cheese'], [537, 'Salad, garden vegetable'],
    [538, 'Salad, green, tossed'], [539, 'Salad, kidney bean'], [540, 'Salad, lettuce & tomato'],
    [541, 'Salad, lettuce cucumber & tomato'], [542, 'Salad, macaroni'], [543, 'Salad, macaroni/tuna'],
    [544, 'Salad, pasta'], [545, 'Salad, pasta, Italian'], [547, 'Salad, pasta, salsa'], [548, 'Salad, perfection'],
    [549, 'Salad, pickled beet & onion'], [550, 'Salad, pineapple rice cup, fluffy'], [551, 'Salad, potato'],
    [552, 'Salad, potato, f/dehyd sliced potatoes'], [553, 'Salad, potato, hot'],
    [554, 'Salad, potato, hot, f/dehyd potatoes'], [555, 'Salad, potato, Mexican style'], [556, 'Salad, rotini, zesty'],
    [557, 'Salad, shrimp'], [558, 'Salad, spinach'], [559, 'Salad, spring'], [560, 'Salad, taco'],
    [562, 'Salad, three bean'], [563, 'Salad, tomato, German style'], [564, 'Salad, tuna'], [565, 'Salad, vegetable'],
    [566, 'Salad, vegetable, tossed'], [567, 'Salad, waldorf'], [568, 'Salmon, cakes'], [569, 'Salmon, loaf'],
    [570, 'Salmon, scalloped, w/peas'], [571, 'Sandwich, bacon lettuce & tomato, tstd'],
    [572, 'Sandwich, bbq beef/sloppy joe'], [573, 'Sandwich, bbq beef/sloppy joe, cnd beef'],
    [574, 'Sandwich, cannonball'], [576, 'Sandwich, cheese, deli'], [577, 'Sandwich, cheese, grilled'],
    [578, 'Sandwich, chicken fillet, breaded, bkd'], [579, 'Sandwich, chicken salad'],
    [580, 'Sandwich, chicken, pita pocket'], [581, 'Sauce, yogurt cucumber'], [582, 'Sandwich, cold cut'],
    [583, 'Sandwich, corned beef'], [584, 'Sandwich, egg salad'], [585, 'Sandwich, fajita beef, on pita'],
    [586, 'Sandwich, fishwich'], [587, 'Sandwich, frankfurter, on roll'], [588, 'Sandwich, Gyros'],
    [589, 'Sandwich, ham'], [590, 'Sandwich, ham egg & cheese, grilled'], [591, 'Sandwich, ham salad'],
    [592, 'Sandwich, Monte Carlo, open-faced'], [594, 'Sandwich, Monte Cristo'], [595, 'Sandwich, Moroccan pockets'],
    [596, 'Sandwich, pastrami, hot'], [597, 'Sandwich, peanut butter & jelly'], [598, 'Sandwich, pepper beef, Italian'],
    [599, 'Sandwich, Reuben, grilled'], [601, 'Sandwich, roast beef, hot'], [603, 'Sandwich, roast pork, hot'],
    [605, 'Sandwich, roast turkey, hot'], [607, 'Sandwich, steak & cheese submarine'], [608, 'Sandwich, submarine'],
    [609, 'Sandwich, taco burger'], [610, 'Sandwich, tuna salad'], [611, 'Sandwich, veal cutlet, Italian, sub'],
    [612, 'Sandwich, Western/Denver'], [614, 'Sauce, cherry'], [615, 'Sauce, cherry jubliee'],
    [616, 'Sauce, cherry, for meat'], [617, 'Sauce, Chinese mustard'], [618, 'Sauce, chocolate'],
    [620, 'Sauce, horseradish'], [621, 'Sauce, lemon'], [623, 'Sauce, mustard'], [624, 'Sauce, pineapple, for ham'],
    [626, 'Sauce, rum'], [627, 'Sauce, seafood cocktail'], [628, 'Sauce, sweet sour'], [630, 'Sauce, taco'],
    [631, 'Sauce, tartar'], [632, 'Sauce, teriyaki'], [635, 'Sauce, vanilla'], [636, 'Sauce, white'],
    [638, 'Sauerkraut, German'], [639, 'Sausage, links, beef & pork, grilled'], [640, 'Sausage, polish, grilled'],
    [641, 'Sausage, pork, patties, grilled'], [642, 'Sausage, turkey, pattie'], [644, 'Scallops, baked'],
    [645, 'Scallops, creole'], [647, 'Scallops, fried'], [648, 'Shortcake, strawberry, f/biscut mix'],
    [649, 'Topping, whipped'], [650, 'Shrimp, cocktail'], [652, 'Shrimp, curry'], [653, 'Shrimp, French fried'],
    [654, 'Shrimp, scampi'], [655, 'Soup, beef, w/vegetables & barley, cnd'], [656, 'Soup, chicken gumbo'],
    [657, 'Soup, chicken mushroom, cnd, condensed'], [658, 'Soup, chicken rice'],
    [659, 'Soup, chicken vegetable/Mulligatawny'], [660, 'Soup, corn chowder'], [661, 'Soup, cream of broccoli, cnd'],
    [662, 'Soup, cream of mushroom'], [663, 'Soup, cream of potato, f/dehyd slices'],
    [664, 'Soup, cream of potato, f/inst potatoes'], [665, 'Soup, creole'], [666, 'Soup, Manhattan clam chowder'],
    [667, 'Soup, navy bean'], [668, 'Soup, New England fish chowder'], [669, 'Soup, onion'], [670, 'Soup, pepper pot'],
    [671, 'Soup, rice w/beef'], [672, 'Soup, Spanish, f/dehyd onion soup mix'], [673, 'Soup, split pea'],
    [674, 'Soup, tomato'], [675, 'Soup, tomato bouillon'], [676, 'Soup, tomato/vegetable, f/dehyd mix'],
    [677, 'Soup, vegetable'], [678, 'Soup, zesty bean'], [679, 'Spinach, club'], [680, 'Spinach, tangy'],
    [681, 'Squash, Hubbard, baked'], [682, 'Squash, Louisiana/smothered'], [683, 'Squash, summer, creole'],
    [684, 'Stew, beef'], [685, 'Stew, beef chunks, w/juices & veg, cnd'], [686, 'Stew, chuck wagon/beans, w/beef'],
    [687, 'Stuffing, corn bread'], [688, 'Stuffing, savory bread'], [689, 'Syrup, maple'],
    [690, 'Tacos, f/ground beef'], [692, 'Tea, hot, brewed'], [693, 'Tea, iced, f/instant'], [694, 'Tomatoes, stewed'],
    [695, 'Topping, orange/coconut'], [696, 'Topping, streusel'], [698, 'Topping, whipped cream'],
    [699, 'Tostadas, beef & bean'], [701, 'Trout, baked, whole'], [702, 'Turkey, cutlet'],
    [703, 'Turkey, nuggets/scallops'], [704, 'Turkey, pattie, grilled'], [705, 'Turkey, roast'],
    [706, 'Turkey, roast, boneless'], [707, 'Turnips, w/bacon'], [708, 'Veal, parmesan'],
    [710, 'Veal, parmesan, cubes'], [711, 'Veal, roast'], [712, 'Veal, steak paprika'],
    [713, 'Veal, steak, Italian style'], [716, 'Wash, egg & milk'], [718, 'Yogurt, soft serve'],
    [719, 'Yogurt, vanilla, soft serve'], [720, 'Apple Brown Betty'], [721, 'Apricots, candied'],
    [723, 'Bread, sourdough starter'], [724, 'Cake, chocolate w/cream cheese icing'],
    [725, 'Cake, chocolate w/vanilla icing'], [726, 'Cake, chocolate, pudding'],
    [727, 'Cake, chocolate, w/fluffy white icing'], [728, 'Cake, marble, w/chocolate icing'],
    [729, 'Cake, white, w/chocolate icing'], [730, 'Candy, divinity'], [731, 'Candy, pralines'], [732, 'Candy, taffy'],
    [733, 'Cookie, snickerdoodle'], [735, 'Crisp, apricot'], [737, 'Dish, crepe, meat filled'],
    [738, 'Dish, manicotti w/cheese filling'], [739, 'Dish, moussaka, lamb & eggplant'], [740, 'Dish, souffle, cheese'],
    [741, 'Dish, spaghetti w/meatballs'], [742, 'Figs, candied'], [743, 'Fudge, peanut butter'],
    [744, 'Fudge, w/marshmallows'], [745, 'Fudge, w/nuts brown sugar'], [746, 'Gelatin Pops, fzn'],
    [747, 'Instant Breakfast, prep w/1% milk'], [748, 'Instant Breakfast, prep w/2% milk'],
    [749, 'Instant Breakfast, prep w/whole milk'], [750, 'Mixed Drink, Bloody Mary'], [751, 'Mixed Drink, Gin & Tonic'],
    [752, 'Mixed Drink, Manhattan'], [753, 'Mixed Drink, Martini'], [754, 'Mixed Drink, Tom Collins'],
    [755, 'Pears, candied'], [756, 'Pie, butterscotch'], [758, 'Pie, rhubarb'], [759, 'Pie, strawberry chiffon'],
    [760, 'Popover, w/2% milk'], [761, 'Popover, w/whole milk'], [763, 'Salad, gelatin, fruity'],
    [765, 'Sandwich, avocado & cheese, on white'], [766, 'Sandwich, avocado & cheese, part wheat'],
    [767, 'Sandwich, avocado & cheese, whole wheat'], [768, 'Sandwich, beef, patty melt, on rye'],
    [769, 'Sandwich, BLT, on part whole wheat'], [770, 'Sandwich, BLT, on white'],
    [771, 'Sandwich, BLT, on whole wheat'], [772, 'Sandwich, chicken salad, on part wheat'],
    [773, 'Sandwich, chicken salad, on white'], [774, 'Sandwich, chicken salad, on whole wheat'],
    [775, 'Sandwich, corned beef & swiss, on rye'], [776, 'Sandwich, egg salad, on part wheat'],
    [777, 'Sandwich, egg salad, on white'], [778, 'Sandwich, egg salad, on whole wheat'],
    [779, 'Sandwich, grilled cheese, part wheat'], [780, 'Sandwich, grilled cheese, white'],
    [781, 'Sandwich, grilled cheese, whole wheat'], [782, 'Sandwich, ham & cheese, on part wheat'],
    [783, 'Sandwich, ham & cheese, on wheat'], [784, 'Sandwich, ham & cheese, on white'],
    [785, 'Sandwich, ham & swiss, on rye'], [786, 'Sandwich, ham salad, on part wheat'],
    [787, 'Sandwich, ham salad, on white'], [788, 'Sandwich, ham salad, on whole wheat'],
    [789, 'Sandwich, ham, on part wheat'], [790, 'Sandwich, ham, on rye'], [791, 'Sandwich, ham, on white'],
    [792, 'Sandwich, ham, on whole wheat'], [793, 'Sandwich, peanut butter/jam, on white'],
    [794, 'Sandwich, peanut butter/jam, part wheat'], [795, 'Sandwich, peanut butter/jam, whole wheat'],
    [796, 'Sandwich, roast beef, on part wheat'], [797, 'Sandwich, roast beef, on white'],
    [798, 'Sandwich, roast beef, on whole wheat'], [799, 'Sandwich, tuna salad, on part wheat'],
    [800, 'Sandwich, tuna salad, on white'], [801, 'Sandwich, tuna salad, on whole wheat'],
    [802, 'Sandwich, turkey ham, on part wheat'], [803, 'Sandwich, turkey ham, on rye'],
    [804, 'Sandwich, turkey ham, on white'], [805, 'Sandwich, turkey ham, on whole wheat'],
    [806, 'Sandwich, turkey ham/cheese, on rye'], [807, 'Sandwich, turkey ham/cheese, on white'],
    [808, 'Sandwich, turkey ham/cheese, whole wheat'], [809, 'Sandwich, turkey, on part wheat'],
    [810, 'Sandwich, turkey, on white'], [811, 'Sandwich, turkey, on whole wheat'], [812, 'Sauce, bearnaise'],
    [813, 'Sauce, bechamel'], [814, 'Sauce, bordelaise'], [815, 'Sauce, curry'], [816, 'Sauce, mornay'],
    [817, 'Soup, beef stock'], [818, 'Soup, menudo, Mexican beef soup'], [819, 'Stew, Brunswick'],
    [820, 'Sweet Roll, cinnamon, w/raisins walnuts'], [821, 'Taco, chicken'], [822, 'Torte, cherry & cream cheese'],
    [823, 'Tostada, bean & chicken'], [824, 'Bean, black, Cuban'], [825, 'Beef, rendang, Malaysian'],
    [826, 'Chicken, kung pao, Chinese'], [827, 'Chicken, malooba, Arabic'], [828, 'Chicken, poulet parisienne, French'],
    [829, 'Chicken, reshmi kebab, Indian'], [830, 'Chicken, sesame, Asian'], [831, 'Chicken, shandong, Chinese'],
    [832, 'Dip, hummus, Greek'], [833, 'Dip, tzatziki, Greek'], [834, 'Dish, Aussie chicken, Australian'],
    [835, 'Sauce, Aussie chicken'], [836, 'Dish, baba ghanoush, Lebanese'], [837, 'Dish, bangers & mash, British'],
    [838, 'Dish, bean & rice, Cuban'], [839, 'Dish, beef lumpia, Filipino'], [840, 'Dish, beef teriyaki, Japanese'],
    [841, 'Dish, beef w/blackeyed beans, Pakistani'], [842, 'Dish, beef, sukiyaki, Japanese'],
    [843, 'Dish, beef, szechuan, Chinese'], [844, 'Dish, bierock casserole, German'],
    [845, 'Dish, braised tofu, Chinese'], [846, 'Dish, broccoli beef, Asian'], [847, 'Dish, bruschetta, Italian'],
    [848, 'Dish, carne con papas, Cuban'], [849, 'Dish, cavatini, Italian'], [850, 'Dish, chicken cashew, Asian'],
    [851, 'Dish, chicken chow mein, Chinese'], [852, 'Dish, chicken coq au vin, French'],
    [853, 'Dish, chicken cordon bleu, French'], [854, 'Dish, chicken curry, Asian'], [855, 'Dish, chicken curry, Thai'],
    [856, 'Dish, chicken lo mein, Chinese'], [857, 'Dish, chicken quesadillas, Mexican'],
    [858, 'Dish, chicken, sweet & sour, Asian'], [859, 'Dish, chop suey, pork, Chinese'],
    [860, 'Dish, currywurst, German'], [861, 'Dish, dolmathes, Greek'], [862, 'Dish, eggplant parmesan, Italian'],
    [863, 'Dish, eggroll w/pork, Chinese'], [864, 'Dish, fava beans, Portuguese'],
    [865, 'Dish, fettuccini alfredo, Italian'], [866, 'Dish, fettucine alfredo,shrimp, Italian'],
    [867, 'Dish, forfar bridies, Scottish'], [868, 'Dish, Hungarian goulash'], [869, 'Dish, jambalaya, French'],
    [870, 'Dish, kaes-spaetzle, Bavarian'], [871, 'Dish, kneophla, German'], [872, 'Dish, kugeli, Lithuanian'],
    [873, 'Dish, lamb feta peppers, Greek'], [874, 'Dish, lancashire hot pot, British'], [875, 'Dish, lasagna, Greek'],
    [876, 'Dish, lasagna, Italian'], [877, 'Dish, lubia polo, Persian'], [878, 'Dish, ma po tofu, Chinese'],
    [879, 'Dish, manicotti, Italian'], [880, 'Dish, marrakesh veg curry, Moroccan'],
    [881, 'Dish, meat & potatoes, Polish'], [882, 'Dish, meat pie, Canadian'], [883, 'Dish, mou shu pork, Chinese'],
    [884, 'Dish, musaka, Greek'], [885, 'Dish, Pad Thai'], [886, 'Dish, pancit, Philippean'],
    [887, 'Dish, pasta carbonara, Italian'], [888, 'Dish, pasta fazul, Italian'], [889, 'Dish, pasta milan, Italian'],
    [890, 'Dish, pasta pomodoro, Italian'], [891, 'Dish, pastachutta, Italian'], [892, 'Dish, pierogi, Polish'],
    [893, 'Dish, plantains, fried, Puerto Rican'], [894, 'Dish, pork ribs, Filipino'],
    [895, 'Dish, quiche lorraine, French'], [896, 'Dish, ratatouille, Italian'], [897, 'Dish, rice bake, Spanish'],
    [898, 'Dish, risotto, Italian'], [899, 'Dish, sausage, Polish'], [900, 'Dish, shrimp chow mein, Chinese'],
    [901, 'Dish, shrimp, egg foo yung, Chinese'], [902, 'Dish, souvlaki, Greek'],
    [903, 'Sauce, souvlaki marinade, Greek'], [904, 'Dish, spanakopita, Greek'], [905, 'Dish, stovies, Scottish'],
    [906, 'Dish, stuffed cabbage, Slovak'], [907, 'Dish, tabbouleh, Lebanese'], [908, 'Dish, tamales, Mexican'],
    [909, 'Dish, vegetarian lo mein, Chinese'], [910, 'Dish, vegetarian pasties, British'],
    [911, 'Dish, wiener schnitzel, German'], [912, 'Dish, yorkshire pudding, British'],
    [913, 'Dish, zwiebelkuchen onion pie, German'], [914, 'Duck, peking, Chinese'], [915, 'Lamb, keema, Indian'],
    [916, 'Pork, barbecued spareribs, Chinese'], [917, 'Pork, Cantonese barbecued, Chinese'],
    [918, 'Pork, ginger, Asian'], [919, 'Pork, marinated, Mediterranean'], [920, 'Pork, patties, sweet & sour, Asian'],
    [921, 'Pork, satay, Indonesian'], [922, 'Pork, satay, Thai'], [923, 'Potato, casserole, Irish'],
    [924, 'Potato, casserole, Moroccan'], [925, 'Salad, chicken, Asian'], [926, 'Sandwich, chicken schwarma, Lebanese'],
    [927, 'Sandwich, midnight medianoche, Cuban'], [929, 'Sauce, curry, Indian'], [930, 'Sauce, Italian gravy w/pork'],
    [932, 'Sauce, spaghetti, Italian'], [933, 'Shrimp, tempura, Japanese'], [934, 'Soup, gazpacho, Spanish'],
    [935, 'Soup, gulyas leves, vegetarian, Hungarian'], [936, 'Soup, harira, Moroccan'],
    [937, 'Soup, hot and sour, Chinese'], [938, 'Soup, minestrone, Italian'], [939, 'Soup, pasta e fagioli, Italian'],
    [940, 'Soup, riboletta, Italian'], [941, 'Soup, sausage tortellini, Italian'],
    [942, 'Soup, sweet & sour cabbage, Ukrainian'], [943, 'Soup, wedding, Italian'], [944, 'Soup, wonton, Chinese'],
    [945, 'Soup, zuppa toscana, Italian'], [946, 'Stew, beef bourguignon, French'], [947, 'Stew, chalau, Afghan'],
    [948, 'Stew, ground nut, African'], [949, 'Stew, lamb w/green beans, Greek'],
    [950, 'Stew, seafood cioppino, Italian'], [951, 'Apples, baked, stuffed'], [952, 'Broth, mushroom'],
    [953, 'Burger/Patty, mushroom lentil'], [954, 'Burger/Patty, veg, American'], [955, 'Burger/patty, veg, European'],
    [956, 'Burger/patty, veg, millet'], [957, 'Burger/patty, veg, Spanish'], [958, 'Burger/patty, veg, vegan'],
    [959, 'Cake, apple spice'], [960, 'Cake, chocolate, cream couscous'], [961, 'Cake, gingerbread, low fat'],
    [962, 'Candy, almost instant'], [963, 'Cappuccino, soy milk'], [964, 'Cashew Balls'],
    [965, 'Cereal, granola, good morning'], [966, 'Cereal, oatmeal, porridge'], [967, 'Cheese, gooda'],
    [968, 'Cheesecake, berry uncheesecake'], [969, 'Cheesecake, lem uncheesecake'], [970, 'Chili, w/texture soy prot'],
    [971, 'Cookie, apple & spice'], [972, 'Cookie, chocolate chews, no bake'], [973, 'Cookie, lemon sesame'],
    [974, 'Crust, crumb'], [975, 'Dessert, apple cranberry kanten'], [976, 'Dessert, apple pear crumble'],
    [977, 'Dip, avocado'], [978, 'Dish, African greens'], [979, 'Dish, bok choy mushrooms ginger'],
    [980, 'Dish, carrots broccoli seaweed'], [981, 'Dish, cauliflower yams'], [982, 'Dish, chickpeas, East Indian'],
    [983, 'Dish, corn, w/red peppers'], [984, 'Dish, East Indian greens'], [985, 'Dish, eggplant, bkd'],
    [986, 'Dish, Far Eastern greens'], [987, 'Dish, figs beans'], [988, 'Dish, green beans, w/black beans'],
    [989, 'Dish, greens tomatoes garlic'], [990, 'Dish, kale red pepper holly ring'], [991, 'Dish, lasagna, al forno'],
    [992, 'Dish, lasagna, cheese cashew'], [993, 'Dish, lentil, dahl-icious'], [994, 'Dish, Mediterranean greens'],
    [995, 'Dish, Middle Eastern greens'], [996, 'Dish, pilaf, currant cumin'], [997, 'Dish, red cabbage w/walnuts'],
    [999, 'Dish, rice, mushroom risotto'], [1000, 'Dish, veg noodles, Szechuan'],
    [1001, 'Dish, veg stir fry w/seasoning-1'], [1002, 'Dish, veg stir fry w/seasoning-2'],
    [1003, 'Dish, vegetable salad roll'], [1004, 'Dish, vegetables w/tofu, curried'], [1005, 'Dish, yams w/kale'],
    [1006, 'Dish, zucchini onion tomato'], [1007, 'Dish, zucchini, w/lentils bulgur'],
    [1008, 'Drink, cran apple cider, hot'], [1009, 'Drink, punch, festive holiday'], [1010, 'Flax, egg replacer'],
    [1011, 'Gomasio'], [1012, 'Gravy, mushroom, light'], [1013, 'Gravy, rosemary'], [1014, 'Gravy, simple brown'],
    [1015, 'Hummus'], [1016, 'Hummus, black bean'], [1017, 'Ice Cream, Vegan Dass'], [1018, 'Kabobs, vegetable'],
    [1019, 'Marinade, tofu'], [1021, 'Mayonnaise, tofu'], [1022, 'Milk, almond'], [1023, 'Muesli, happy heart'],
    [1024, 'Muffin, blueberry corn'], [1025, 'Muffin, cranberry pecan'], [1026, 'Muffin, raisin & walnut'],
    [1028, 'Pancakes, fruity whole grain'], [1029, 'Pate, hazelnut'], [1030, 'Pesto'],
    [1033, 'Pizza, veggie pepperoni'], [1034, 'Potatoes, lemon rstd'], [1035, 'Potatoes, mashed w/coriander'],
    [1036, 'Potatoes, scalloped, dijon'], [1037, 'Potatoes, subji'], [1038, 'Potatoes, wedges, seasoned'],
    [1039, 'Pudding, brown rice'], [1040, 'Pudding, chocolate soy'], [1041, 'Pudding, figgy'],
    [1042, 'Pudding, whole grain'], [1043, 'Relish, cranberry ginger'], [1044, 'Roll Up, African style'],
    [1045, 'Roll Up, Indonesian style'], [1046, 'Roll Up, Italian style'], [1047, 'Roll Up, Japanese style'],
    [1049, 'Roll Up, Mexican style'], [1050, 'Roll Up, Middle Eastern style'], [1051, 'Salad Dressing, lemon tahini'],
    [1052, 'Salad Dressing, caesar'], [1053, 'Salad Dressing, cucumber dill'], [1055, 'Salad Dressing, orange mint'],
    [1056, 'Salad Dressing, oriental'], [1057, 'Salad Dressing, Raspberry Vinaigrette'],
    [1058, 'Salad Dressing, sesame tahini'], [1059, 'Salad Dressing, tomato herb'],
    [1061, 'Salad Dressing, vinegar & flax'], [1062, 'Salad, apple walnut'], [1063, 'Salad, avocado grapefruit'],
    [1064, 'Salad, basmati rice'], [1065, 'Salad, beet kale'], [1066, 'Salad, caesar'],
    [1068, 'Salad, calcium-rich greens'], [1069, 'Salad, couscous'], [1070, 'Salad, deep green leafy'],
    [1071, 'Salad, fruit, fresh'], [1072, 'Salad, pasta, Thai w/peanut sce'], [1073, 'Sauce, spicy peanut'],
    [1074, 'Salad, potato dill'], [1075, 'Salad, potato w/tofu mayonnaise'], [1077, 'Salad, quinoa, w/lime dressing'],
    [1078, 'Salad, sun-dried tomato & rice'], [1079, 'Salad, wild garden'], [1080, 'Sandwich, tofu, open faced'],
    [1081, 'Sauce, blueberry orange'], [1082, 'Sauce, curry, in a hurry'], [1083, 'Sauce, fruit'],
    [1086, 'Sauce, tomato miso'], [1087, 'Sauce, tomato miso, w/aduki'], [1088, 'Seeds, sunflower, tstd'],
    [1089, 'Shake, orange fruit'], [1090, 'Shake, strawberry fruit'], [1091, 'Soup, black bean'],
    [1092, 'Soup, carrot & yam'], [1093, 'Soup, creamy vegetable'], [1094, 'Soup, green sea'], [1095, 'Soup, lentil'],
    [1096, 'Soup, Minestrone'], [1097, 'Soup, miso ginger'], [1098, 'Soup, Mulligatawny'],
    [1099, 'Soup, spicy eggplant'], [1100, 'Soup, split pea w/veggie bacon'],
    [1101, 'Soup, vegetable cream, non dairy'], [1102, 'Soup, vegetable noodle'], [1103, 'Spinach, w/garam masala'],
    [1104, 'Spinach, w/gomasio'], [1105, 'Spread, eggless egg salad'], [1106, 'Spread, Gee Whiz'],
    [1107, 'Spread, Morrocc-un-butter'], [1108, 'Spread, rstd garlic & yam'], [1109, 'Spread, sandwich, carrot/tahini'],
    [1110, 'Spread, sandwich, curry'], [1111, 'Squash, spaghetti'], [1112, 'Squash, stuffed, winter'],
    [1113, 'Stew, African'], [1114, 'Stew, black bean, savory'], [1115, 'Stew, two-bean w/dumplings'], [1116, 'Sushi'],
    [1117, 'Taco, w/tofu filling'], [1118, 'Taco, w/tofu filling/garnishes'], [1119, 'Tart, blueberry mince'],
    [1120, 'Tempeh, lemon ginger'], [1121, 'Tofu, crispy fingers'], [1122, 'Tofu, red star fingers'],
    [1123, 'Tofu, scrambled'], [1124, 'Tofu, scrambled, w/salsa'], [1125, 'Tofu, sweet & sour'],
    [1126, 'Tofu, teriyaki'], [1127, 'Tomato sauce, chunky red lentil'], [1128, 'Topping, holiday pie'],
    [1129, 'Vegetables, Roasted Roots'],
  ];

  return [
    new Map(recipe_names),
    recipe_names.map(recipe => ({label: recipe[1], value: recipe[0]}))
  ];
})();

